# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.security_rules_api import SecurityRulesApi


class TestSecurityRulesApi(unittest.TestCase):
    """SecurityRulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityRulesApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_security_rule_protocols(self) -> None:
        """Test case for retrieve_security_rule_protocols

        Retrieve Security Rule Protocols
        """
        pass


if __name__ == '__main__':
    unittest.main()
