# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.rbac_role_api import RbacRoleApi


class TestRbacRoleApi(unittest.TestCase):
    """RbacRoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RbacRoleApi()

    def tearDown(self) -> None:
        pass

    def test_create_rbac_role(self) -> None:
        """Test case for create_rbac_role

        Create RBAC Role
        """
        pass

    def test_delete_a_rbac_role(self) -> None:
        """Test case for delete_a_rbac_role

        Delete a RBAC Role
        """
        pass

    def test_get_a_rbac_role_detail(self) -> None:
        """Test case for get_a_rbac_role_detail

        Get a RBAC Role Detail
        """
        pass

    def test_list_rbac_roles(self) -> None:
        """Test case for list_rbac_roles

        List RBAC Roles
        """
        pass

    def test_update_a_rbac_role(self) -> None:
        """Test case for update_a_rbac_role

        Update a RBAC Role
        """
        pass


if __name__ == '__main__':
    unittest.main()
