# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.deployment_api import DeploymentApi


class TestDeploymentApi(unittest.TestCase):
    """DeploymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentApi()

    def tearDown(self) -> None:
        pass

    def test_delete_deployment(self) -> None:
        """Test case for delete_deployment

        Delete Deployment
        """
        pass

    def test_details_of_deployment_by_id(self) -> None:
        """Test case for details_of_deployment_by_id

        Details of Deployment by ID
        """
        pass

    def test_list_deployments(self) -> None:
        """Test case for list_deployments

        List Deployments
        """
        pass

    def test_start_deployment(self) -> None:
        """Test case for start_deployment

        Start Deployment
        """
        pass


if __name__ == '__main__':
    unittest.main()
