# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.firewall_attachment_api import FirewallAttachmentApi


class TestFirewallAttachmentApi(unittest.TestCase):
    """FirewallAttachmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FirewallAttachmentApi()

    def tearDown(self) -> None:
        pass

    def test_attach_firewall_to_vms(self) -> None:
        """Test case for attach_firewall_to_vms

        Attach Firewalls to VMs
        """
        pass


if __name__ == '__main__':
    unittest.main()
