# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.flavor_item_get_response import FlavorItemGetResponse

class TestFlavorItemGetResponse(unittest.TestCase):
    """FlavorItemGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlavorItemGetResponse:
        """Test FlavorItemGetResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlavorItemGetResponse`
        """
        model = FlavorItemGetResponse()
        if include_optional:
            return FlavorItemGetResponse(
                gpu = '',
                region_name = '',
                flavors = [
                    hyperstack.models.flavor_fields.FlavorFields(
                        id = 56, 
                        name = '', 
                        region_name = '', 
                        cpu = 56, 
                        ram = 1.337, 
                        disk = 56, 
                        gpu = '', 
                        gpu_count = 56, 
                        stock_available = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return FlavorItemGetResponse(
        )
        """

    def testFlavorItemGetResponse(self):
        """Test FlavorItemGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
