# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationApi()

    def tearDown(self) -> None:
        pass

    def test_get_organization_info(self) -> None:
        """Test case for get_organization_info

        Organization Info
        """
        pass

    def test_remove_a_member_from_organization(self) -> None:
        """Test case for remove_a_member_from_organization

        Remove a member from organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
