# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.admin_bootstrap_environment_payload import AdminBootstrapEnvironmentPayload

class TestAdminBootstrapEnvironmentPayload(unittest.TestCase):
    """AdminBootstrapEnvironmentPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminBootstrapEnvironmentPayload:
        """Test AdminBootstrapEnvironmentPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminBootstrapEnvironmentPayload`
        """
        model = AdminBootstrapEnvironmentPayload()
        if include_optional:
            return AdminBootstrapEnvironmentPayload(
                org_id = 56
            )
        else:
            return AdminBootstrapEnvironmentPayload(
                org_id = 56,
        )
        """

    def testAdminBootstrapEnvironmentPayload(self):
        """Test AdminBootstrapEnvironmentPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
