# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.discount_plan_fields import DiscountPlanFields

class TestDiscountPlanFields(unittest.TestCase):
    """DiscountPlanFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscountPlanFields:
        """Test DiscountPlanFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscountPlanFields`
        """
        model = DiscountPlanFields()
        if include_optional:
            return DiscountPlanFields(
                id = 56,
                resource_id = 56,
                resource_name = '',
                resource_count = 56,
                discount_type = '',
                discount_code = '',
                discount_percent = 1.337,
                discount_amount = 1.337,
                discount_status = ''
            )
        else:
            return DiscountPlanFields(
        )
        """

    def testDiscountPlanFields(self):
        """Test DiscountPlanFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
