# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.virtual_machine_events_api import VirtualMachineEventsApi


class TestVirtualMachineEventsApi(unittest.TestCase):
    """VirtualMachineEventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VirtualMachineEventsApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_all_of_the_instance_events(self) -> None:
        """Test case for fetch_all_of_the_instance_events

        Fetch all of the instance events
        """
        pass


if __name__ == '__main__':
    unittest.main()
