# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.attach_callback_response import AttachCallbackResponse

class TestAttachCallbackResponse(unittest.TestCase):
    """AttachCallbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttachCallbackResponse:
        """Test AttachCallbackResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttachCallbackResponse`
        """
        model = AttachCallbackResponse()
        if include_optional:
            return AttachCallbackResponse(
                status = True,
                message = '',
                url = ''
            )
        else:
            return AttachCallbackResponse(
        )
        """

    def testAttachCallbackResponse(self):
        """Test AttachCallbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
