# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.alive_api import AliveApi


class TestAliveApi(unittest.TestCase):
    """AliveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AliveApi()

    def tearDown(self) -> None:
        pass

    def test_get_alive(self) -> None:
        """Test case for get_alive

        GET: Alive
        """
        pass


if __name__ == '__main__':
    unittest.main()
