# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.instance_events_fields import InstanceEventsFields

class TestInstanceEventsFields(unittest.TestCase):
    """InstanceEventsFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceEventsFields:
        """Test InstanceEventsFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceEventsFields`
        """
        model = InstanceEventsFields()
        if include_optional:
            return InstanceEventsFields(
                instance_id = 56,
                user_id = 56,
                org_id = 56,
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = '',
                reason = '',
                object = '',
                message = ''
            )
        else:
            return InstanceEventsFields(
        )
        """

    def testInstanceEventsFields(self):
        """Test InstanceEventsFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
