# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.get_contracts_list_response_model import GetContractsListResponseModel

class TestGetContractsListResponseModel(unittest.TestCase):
    """GetContractsListResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetContractsListResponseModel:
        """Test GetContractsListResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetContractsListResponseModel`
        """
        model = GetContractsListResponseModel()
        if include_optional:
            return GetContractsListResponseModel(
                status = True,
                message = '',
                contracts = [
                    hyperstack.models.admin_contract_fields.AdminContractFields(
                        id = 56, 
                        org_name = '', 
                        description = '', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expiration_policy = 56, 
                        status = '', 
                        gpu_name = '', 
                        percent = 1.337, 
                        amount = 1.337, 
                        discount_type = '', 
                        resource_count = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                count = 56
            )
        else:
            return GetContractsListResponseModel(
        )
        """

    def testGetContractsListResponseModel(self):
        """Test GetContractsListResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
