# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.profile_api import ProfileApi


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfileApi()

    def tearDown(self) -> None:
        pass

    def test_create_profile(self) -> None:
        """Test case for create_profile

        Create profile
        """
        pass

    def test_delete_profile(self) -> None:
        """Test case for delete_profile

        Delete profile
        """
        pass

    def test_list_profiles(self) -> None:
        """Test case for list_profiles

        List profiles
        """
        pass

    def test_retrieve_profile_details(self) -> None:
        """Test case for retrieve_profile_details

        Retrieve profile details
        """
        pass


if __name__ == '__main__':
    unittest.main()
