# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.floating_ip_api import FloatingIpApi


class TestFloatingIpApi(unittest.TestCase):
    """FloatingIpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FloatingIpApi()

    def tearDown(self) -> None:
        pass

    def test_attach_floating_ip_to_instance(self) -> None:
        """Test case for attach_floating_ip_to_instance

        Attach Floating IP to Instance
        """
        pass

    def test_detach_floating_ip_to_instance(self) -> None:
        """Test case for detach_floating_ip_to_instance

        Detach Floating IP to Instance
        """
        pass


if __name__ == '__main__':
    unittest.main()
