# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.flavor_admin_response import FlavorAdminResponse

class TestFlavorAdminResponse(unittest.TestCase):
    """FlavorAdminResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlavorAdminResponse:
        """Test FlavorAdminResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlavorAdminResponse`
        """
        model = FlavorAdminResponse()
        if include_optional:
            return FlavorAdminResponse(
                status = True,
                message = '',
                flavor = hyperstack.models.flavor_admin_response_flavors.FlavorAdminResponseFlavors(
                    id = 56, 
                    name = '', 
                    description = '', 
                    openstack_id = '', 
                    region_id = 56, 
                    region = '', 
                    cpu = 56, 
                    ram = 1.337, 
                    disk = 56, 
                    ephemeral = 56, 
                    gpu = '', 
                    gpu_count = 56, 
                    order = 56, 
                    is_public = True, 
                    is_custom = True, 
                    status = '', 
                    organizations = [
                        56
                        ], 
                    flavors = [
                        ''
                        ], 
                    projects = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return FlavorAdminResponse(
        )
        """

    def testFlavorAdminResponse(self):
        """Test FlavorAdminResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
