# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.vnc_url_api import VncUrlApi


class TestVncUrlApi(unittest.TestCase):
    """VncUrlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VncUrlApi()

    def tearDown(self) -> None:
        pass

    def test_get_vnc_console_link(self) -> None:
        """Test case for get_vnc_console_link

        Get VNC Console Link
        """
        pass

    def test_request_console(self) -> None:
        """Test case for request_console

        Request Instance Console
        """
        pass


if __name__ == '__main__':
    unittest.main()
