# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.get_all_discounts_fields import GetAllDiscountsFields

class TestGetAllDiscountsFields(unittest.TestCase):
    """GetAllDiscountsFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllDiscountsFields:
        """Test GetAllDiscountsFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllDiscountsFields`
        """
        model = GetAllDiscountsFields()
        if include_optional:
            return GetAllDiscountsFields(
                org_id = 56,
                org_name = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                discount_status = '',
                discount_resources = [
                    hyperstack.models.discount_resource_fields.DiscountResourceFields(
                        resource_id = 56, 
                        discount_percent = 1.337, )
                    ]
            )
        else:
            return GetAllDiscountsFields(
        )
        """

    def testGetAllDiscountsFields(self):
        """Test GetAllDiscountsFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
