# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.environment_api import EnvironmentApi


class TestEnvironmentApi(unittest.TestCase):
    """EnvironmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnvironmentApi()

    def tearDown(self) -> None:
        pass

    def test_create_environment(self) -> None:
        """Test case for create_environment

        Create environment
        """
        pass

    def test_delete_environment(self) -> None:
        """Test case for delete_environment

        Delete environment
        """
        pass

    def test_list_environments(self) -> None:
        """Test case for list_environments

        List environments
        """
        pass

    def test_retrieve_environment(self) -> None:
        """Test case for retrieve_environment

        Retrieve environment
        """
        pass

    def test_update_environment(self) -> None:
        """Test case for update_environment

        Update environment
        """
        pass


if __name__ == '__main__':
    unittest.main()
