# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.admin_organizations_response_model import AdminOrganizationsResponseModel

class TestAdminOrganizationsResponseModel(unittest.TestCase):
    """AdminOrganizationsResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminOrganizationsResponseModel:
        """Test AdminOrganizationsResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminOrganizationsResponseModel`
        """
        model = AdminOrganizationsResponseModel()
        if include_optional:
            return AdminOrganizationsResponseModel(
                status = True,
                message = '',
                organizations = [
                    hyperstack.models.organization_fields.OrganizationFields(
                        id = 56, 
                        name = '', 
                        credit = 56, 
                        threshold = 56, 
                        total_instances = 56, 
                        total_volumes = 56, 
                        total_containers = 56, 
                        total_clusters = 56, 
                        users = [
                            hyperstack.models.organization_user_response_model.OrganizationUserResponseModel(
                                id = 56, 
                                sub = '', 
                                email = '', 
                                username = '', 
                                name = '', 
                                role = '', 
                                rbac_roles = [
                                    hyperstack.models.rbac_role_field.RbacRoleField(
                                        name = '', )
                                    ], 
                                joined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                organization_count = 56
            )
        else:
            return AdminOrganizationsResponseModel(
        )
        """

    def testAdminOrganizationsResponseModel(self):
        """Test AdminOrganizationsResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
