# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.admin_image_list_admin_response import AdminImageListAdminResponse

class TestAdminImageListAdminResponse(unittest.TestCase):
    """AdminImageListAdminResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminImageListAdminResponse:
        """Test AdminImageListAdminResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminImageListAdminResponse`
        """
        model = AdminImageListAdminResponse()
        if include_optional:
            return AdminImageListAdminResponse(
                status = True,
                message = '',
                data = [
                    hyperstack.models.admin_image_admin_fields.AdminImageAdminFields(
                        id = 56, 
                        name = '', 
                        openstack_id = '', 
                        region_id = 56, 
                        region_name = '', 
                        type = '', 
                        version = '', 
                        size = 56, 
                        is_public = True, 
                        description = '', 
                        labels = [
                            hyperstack.models.lable_resonse.LableResonse(
                                id = 56, 
                                label = '', )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return AdminImageListAdminResponse(
        )
        """

    def testAdminImageListAdminResponse(self):
        """Test AdminImageListAdminResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
