# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.firewalls_api import FirewallsApi


class TestFirewallsApi(unittest.TestCase):
    """FirewallsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FirewallsApi()

    def tearDown(self) -> None:
        pass

    def test_add_rules_to_firewall(self) -> None:
        """Test case for add_rules_to_firewall

        Add Rules to Firewall
        """
        pass

    def test_create_firewall(self) -> None:
        """Test case for create_firewall

        Create Firewall
        """
        pass

    def test_delete_firewall(self) -> None:
        """Test case for delete_firewall

        Delete Firewall
        """
        pass

    def test_delete_firewall_rules_from_firewall(self) -> None:
        """Test case for delete_firewall_rules_from_firewall

        Delete Firewall Rules from Firewall
        """
        pass

    def test_details_of_firewall_by_id(self) -> None:
        """Test case for details_of_firewall_by_id

        Details of Firewall by ID
        """
        pass

    def test_retrieve_firewalls(self) -> None:
        """Test case for retrieve_firewalls

        Retrieve Firewalls
        """
        pass


if __name__ == '__main__':
    unittest.main()
