# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.virtual_machine_api import VirtualMachineApi


class TestVirtualMachineApi(unittest.TestCase):
    """VirtualMachineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VirtualMachineApi()

    def tearDown(self) -> None:
        pass

    def test_add_security_rule(self) -> None:
        """Test case for add_security_rule

        Add Security Rule
        """
        pass

    def test_create_instances(self) -> None:
        """Test case for create_instances

        Create Instances
        """
        pass

    def test_delete_a_security_rule(self) -> None:
        """Test case for delete_a_security_rule

        Delete a security group rule
        """
        pass

    def test_delete_an_instance(self) -> None:
        """Test case for delete_an_instance

        Delete an instance
        """
        pass

    def test_get_an_instance_details(self) -> None:
        """Test case for get_an_instance_details

        Get an instance details
        """
        pass

    def test_hard_reboot_instance(self) -> None:
        """Test case for hard_reboot_instance

        Hard Reboot Instance
        """
        pass

    def test_hibernate_instance(self) -> None:
        """Test case for hibernate_instance

        Hibernate Instance
        """
        pass

    def test_list_instances(self) -> None:
        """Test case for list_instances

        List Instances
        """
        pass

    def test_resize_virtual_machine(self) -> None:
        """Test case for resize_virtual_machine

        Resize Virtual Machine
        """
        pass

    def test_restore_instance_from_hibernation(self) -> None:
        """Test case for restore_instance_from_hibernation

        Restore Instance from Hibernation
        """
        pass

    def test_retrieved_metrics_successfully(self) -> None:
        """Test case for retrieved_metrics_successfully

        Get instance metrics
        """
        pass

    def test_start_instance(self) -> None:
        """Test case for start_instance

        Start Instance
        """
        pass

    def test_stop_instance(self) -> None:
        """Test case for stop_instance

        Stop Instance
        """
        pass


if __name__ == '__main__':
    unittest.main()
