# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.admin_organization_summary_fields import AdminOrganizationSummaryFields

class TestAdminOrganizationSummaryFields(unittest.TestCase):
    """AdminOrganizationSummaryFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminOrganizationSummaryFields:
        """Test AdminOrganizationSummaryFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminOrganizationSummaryFields`
        """
        model = AdminOrganizationSummaryFields()
        if include_optional:
            return AdminOrganizationSummaryFields(
                id = 56,
                name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AdminOrganizationSummaryFields(
                id = 56,
                name = '',
        )
        """

    def testAdminOrganizationSummaryFields(self):
        """Test AdminOrganizationSummaryFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
