# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.policy_api import PolicyApi


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyApi()

    def tearDown(self) -> None:
        pass

    def test_list_policies(self) -> None:
        """Test case for list_policies

        List Policies
        """
        pass


if __name__ == '__main__':
    unittest.main()
