# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.user_detail_choice_api import UserDetailChoiceApi


class TestUserDetailChoiceApi(unittest.TestCase):
    """UserDetailChoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserDetailChoiceApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_default_flavors_and_images_for_user(self) -> None:
        """Test case for retrieve_default_flavors_and_images_for_user

        Retrieve default flavors and images for user
        """
        pass


if __name__ == '__main__':
    unittest.main()
