# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.create_gpu import CreateGPU

class TestCreateGPU(unittest.TestCase):
    """CreateGPU unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateGPU:
        """Test CreateGPU
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateGPU`
        """
        model = CreateGPU()
        if include_optional:
            return CreateGPU(
                name = '',
                regions = [
                    ''
                    ],
                example_metadata = ''
            )
        else:
            return CreateGPU(
                name = '',
        )
        """

    def testCreateGPU(self):
        """Test CreateGPU"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
