# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.firewall_attachment_model import FirewallAttachmentModel

class TestFirewallAttachmentModel(unittest.TestCase):
    """FirewallAttachmentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FirewallAttachmentModel:
        """Test FirewallAttachmentModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FirewallAttachmentModel`
        """
        model = FirewallAttachmentModel()
        if include_optional:
            return FirewallAttachmentModel(
                id = 56,
                status = '',
                vm = hyperstack.models.firewall_attachment_vm_model.FirewallAttachmentVMModel(
                    id = 56, 
                    name = '', 
                    flavor = '', 
                    environment = '', 
                    status = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FirewallAttachmentModel(
        )
        """

    def testFirewallAttachmentModel(self):
        """Test FirewallAttachmentModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
