# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.volume_api import VolumeApi


class TestVolumeApi(unittest.TestCase):
    """VolumeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VolumeApi()

    def tearDown(self) -> None:
        pass

    def test_create_volume(self) -> None:
        """Test case for create_volume

        Create Volume
        """
        pass

    def test_delete_volume(self) -> None:
        """Test case for delete_volume

        Delete Volume
        """
        pass

    def test_get_volume_types(self) -> None:
        """Test case for get_volume_types

        GET Volume Types
        """
        pass

    def test_list_volumes(self) -> None:
        """Test case for list_volumes

        List Volumes
        """
        pass


if __name__ == '__main__':
    unittest.main()
