# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.attach_volumes import AttachVolumes

class TestAttachVolumes(unittest.TestCase):
    """AttachVolumes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttachVolumes:
        """Test AttachVolumes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttachVolumes`
        """
        model = AttachVolumes()
        if include_optional:
            return AttachVolumes(
                status = True,
                message = '',
                volume_attachments = [
                    hyperstack.models.attach_volume_fields.AttachVolumeFields(
                        id = 56, 
                        instance_id = 56, 
                        volume_id = 56, 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return AttachVolumes(
        )
        """

    def testAttachVolumes(self):
        """Test AttachVolumes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
