# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.compliance_fields import ComplianceFields

class TestComplianceFields(unittest.TestCase):
    """ComplianceFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceFields:
        """Test ComplianceFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceFields`
        """
        model = ComplianceFields()
        if include_optional:
            return ComplianceFields(
                gpu_model = '',
                cpu = [
                    56
                    ],
                ram = [
                    56
                    ],
                hdd = [
                    56
                    ]
            )
        else:
            return ComplianceFields(
        )
        """

    def testComplianceFields(self):
        """Test ComplianceFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
