# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.internal_instance_flavor_fields import InternalInstanceFlavorFields

class TestInternalInstanceFlavorFields(unittest.TestCase):
    """InternalInstanceFlavorFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalInstanceFlavorFields:
        """Test InternalInstanceFlavorFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalInstanceFlavorFields`
        """
        model = InternalInstanceFlavorFields()
        if include_optional:
            return InternalInstanceFlavorFields(
                id = 56,
                name = '',
                region_name = '',
                cpu = 56,
                ram = 56,
                disk = 56,
                gpu = '',
                gpu_count = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return InternalInstanceFlavorFields(
        )
        """

    def testInternalInstanceFlavorFields(self):
        """Test InternalInstanceFlavorFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
