# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.api_key_fields import ApiKeyFields

class TestApiKeyFields(unittest.TestCase):
    """ApiKeyFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyFields:
        """Test ApiKeyFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyFields`
        """
        model = ApiKeyFields()
        if include_optional:
            return ApiKeyFields(
                key = ''
            )
        else:
            return ApiKeyFields(
        )
        """

    def testApiKeyFields(self):
        """Test ApiKeyFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
