# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.create_instances_payload import CreateInstancesPayload

class TestCreateInstancesPayload(unittest.TestCase):
    """CreateInstancesPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInstancesPayload:
        """Test CreateInstancesPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInstancesPayload`
        """
        model = CreateInstancesPayload()
        if include_optional:
            return CreateInstancesPayload(
                name = '',
                environment_name = '',
                image_name = '',
                volume_name = '',
                create_bootable_volume = True,
                flavor_name = '',
                flavor = hyperstack.models.flavor_object_fields.FlavorObjectFields(
                    cpu = 56, 
                    ram = 1.337, 
                    disk = 56, 
                    gpu = '', 
                    gpu_count = 56, ),
                key_name = '',
                user_data = '',
                callback_url = '',
                assign_floating_ip = True,
                profile = hyperstack.models.profile_object_fields.ProfileObjectFields(
                    name = '', 
                    description = '', ),
                count = 56
            )
        else:
            return CreateInstancesPayload(
                name = '',
                environment_name = '',
                key_name = '',
                count = 56,
        )
        """

    def testCreateInstancesPayload(self):
        """Test CreateInstancesPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
