# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.compliance_api import ComplianceApi


class TestComplianceApi(unittest.TestCase):
    """ComplianceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComplianceApi()

    def tearDown(self) -> None:
        pass

    def test_create_compliance(self) -> None:
        """Test case for create_compliance

        Create compliance
        """
        pass

    def test_delete_a_compliance(self) -> None:
        """Test case for delete_a_compliance

        Delete a compliance
        """
        pass

    def test_retrieve_compliance(self) -> None:
        """Test case for retrieve_compliance

        Retrieve GPU compliance
        """
        pass

    def test_update_a_compliance(self) -> None:
        """Test case for update_a_compliance

        Update a compliance
        """
        pass


if __name__ == '__main__':
    unittest.main()
