# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.api_key_verify_fields import ApiKeyVerifyFields

class TestApiKeyVerifyFields(unittest.TestCase):
    """ApiKeyVerifyFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyVerifyFields:
        """Test ApiKeyVerifyFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyVerifyFields`
        """
        model = ApiKeyVerifyFields()
        if include_optional:
            return ApiKeyVerifyFields(
                user_id = 56,
                org_id = 56,
                user_role = '',
                sub = ''
            )
        else:
            return ApiKeyVerifyFields(
        )
        """

    def testApiKeyVerifyFields(self):
        """Test ApiKeyVerifyFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
