# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.customer_payload import CustomerPayload

class TestCustomerPayload(unittest.TestCase):
    """CustomerPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerPayload:
        """Test CustomerPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerPayload`
        """
        model = CustomerPayload()
        if include_optional:
            return CustomerPayload(
                id = 56,
                plan_type = ''
            )
        else:
            return CustomerPayload(
                id = 56,
                plan_type = '',
        )
        """

    def testCustomerPayload(self):
        """Test CustomerPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
