# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.gpu import GPU

class TestGPU(unittest.TestCase):
    """GPU unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GPU:
        """Test GPU
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GPU`
        """
        model = GPU()
        if include_optional:
            return GPU(
                status = True,
                message = '',
                gpu = hyperstack.models.gpu_fields.GPUFields(
                    id = 56, 
                    name = '', 
                    regions = [
                        hyperstack.models.gpu_region_fields.GPURegionFields(
                            id = 56, 
                            name = '', )
                        ], 
                    example_metadata = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GPU(
        )
        """

    def testGPU(self):
        """Test GPU"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
