# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.billingimmuneresources import Billingimmuneresources

class TestBillingimmuneresources(unittest.TestCase):
    """Billingimmuneresources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Billingimmuneresources:
        """Test Billingimmuneresources
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Billingimmuneresources`
        """
        model = Billingimmuneresources()
        if include_optional:
            return Billingimmuneresources(
                resource_id = 56,
                resource_type = '',
                organization_id = 56
            )
        else:
            return Billingimmuneresources(
        )
        """

    def testBillingimmuneresources(self):
        """Test Billingimmuneresources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
