# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.payment_details_response import PaymentDetailsResponse

class TestPaymentDetailsResponse(unittest.TestCase):
    """PaymentDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDetailsResponse:
        """Test PaymentDetailsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDetailsResponse`
        """
        model = PaymentDetailsResponse()
        if include_optional:
            return PaymentDetailsResponse(
                message = '',
                status = True,
                data = hyperstack.models.payment_details_fields.PaymentDetailsFields(
                    amount = 1.337, 
                    currency = '', 
                    paid_from = '', 
                    status = '', 
                    gateway_response = '', 
                    description = '', 
                    transaction_id = '', 
                    payment_id = '', 
                    updated_at = '', )
            )
        else:
            return PaymentDetailsResponse(
        )
        """

    def testPaymentDetailsResponse(self):
        """Test PaymentDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
