# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.payment_initiate_response import PaymentInitiateResponse

class TestPaymentInitiateResponse(unittest.TestCase):
    """PaymentInitiateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentInitiateResponse:
        """Test PaymentInitiateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentInitiateResponse`
        """
        model = PaymentInitiateResponse()
        if include_optional:
            return PaymentInitiateResponse(
                message = '',
                status = True,
                data = hyperstack.models.payment_initiate_fields.PaymentInitiateFields(
                    payment_id = '', )
            )
        else:
            return PaymentInitiateResponse(
        )
        """

    def testPaymentInitiateResponse(self):
        """Test PaymentInitiateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
