# coding: utf-8

"""
    Infrahub-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperstack.models.admin_flavor_resource import AdminFlavorResource
from typing import Optional, Set
from typing_extensions import Self

class AdminClusterResource(BaseModel):
    """
    AdminClusterResource
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    kubernetes_version: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    master_count: Optional[StrictInt] = None
    node_count: Optional[StrictInt] = None
    node_flavor: Optional[AdminFlavorResource] = None
    enable_public_ip: Optional[StrictBool] = None
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "kubernetes_version", "status", "master_count", "node_count", "node_flavor", "enable_public_ip", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminClusterResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of node_flavor
        if self.node_flavor:
            _dict['node_flavor'] = self.node_flavor.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminClusterResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "kubernetes_version": obj.get("kubernetes_version"),
            "status": obj.get("status"),
            "master_count": obj.get("master_count"),
            "node_count": obj.get("node_count"),
            "node_flavor": AdminFlavorResource.from_dict(obj["node_flavor"]) if obj.get("node_flavor") is not None else None,
            "enable_public_ip": obj.get("enable_public_ip"),
            "created_at": obj.get("created_at")
        })
        return _obj


